project:
  type: website
  output-dir: ../_site
  preview:
    port: 4444

website:
  title: "Callum Edwards"
  site-url: https://www.callumre.com
  description: "Callum Edwards Blog"
  favicon: logo.png
  # margin-header: subscribe.html
  page-navigation: true
  open-graph: true  # https://quarto.org/docs/websites/website-tools.html#open-graph
  google-analytics: G-X9YW0JXMNV
  repo-url: https://github.com/CallumREdwards/callumre.com
  repo-actions: [issue]
  navbar:
    left:
      - text: "About"
        file: index.qmd 
      - text: "Blog"
        file: posts.qmd
    right:
      - text: RSS
        icon: rss
        href: index.xml
      - icon: github
        href: https://github.com/CallumREdwards
      - icon: linkedin
        href: https://www.linkedin.com/in/callum-edwards-783073194
  page-footer:
    center: © Callum Edwards 2024 • [Feedback](hi.callumre@gmail.com) • [RSS](https://callumre.com/index.xml)
format:
  html:
    theme:
      light: [default, styles/light.scss]
      dark: [darkly, styles/dark.scss]
    css: styles.css
    smooth-scroll: true
    code-copy: true

# default  x
# cerulean
# cosmo
# cyborg
# darkly
# flatly  x
# journal
# litera
# lumen
# lux
# materia
# minty
# morph
# pulse
# quartz
# sandstone
# simplex
# sketchy
# slate
# solar
# spacelab
# superhero
# united
# vapor
# yeti
# zephyr


execute:
  # https://quarto.org/docs/publishing/netlify.html#freezing-computations
  freeze: auto
