project:
  type: website
  output-dir: ../_site

website:
  title: "Callum Edwards"
  site-url: https://www.callumre.com
  description: "Callum Edwards Blog"
  margin-header: subscribe.html
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - about.qmd 
    right:
      - icon: rss
        href: index.xml
      - icon: github
        href: https://github.com/CallumREdwards
      - icon: twitter
        href: https://twitter.com/CallumE35268498
format:
  html:
    theme: lux
    css: styles.css

execute:
  # https://quarto.org/docs/publishing/netlify.html#freezing-computations
  freeze: auto
